### ISSUE TITLE
Document the output of the facet and its response 

### ISSUE THREAD

**Issue by sumit-158** [openfoodfacts/facets-knowledge-panels#20]
### Story
- Document knowledge-panel response so user could understand the project easily 
- with OpenApi

**Comment by alexgarel** [comment]
@sumit-158 while documenting you might also review you knowledge panels for many of them are not compatible with current informal spec.
Look at https://world.openfoodfacts.org/api/v2/product/3017620422003/nutella-ferrero-nutella?fields=knowledge_panels to see what exists.

**Comment by sumit-158** [comment]
> 

@alexgarel This is different Kp, I'm confuse do you mean I have to make current kp spec something like [https://world.openfoodfacts.org/api/v2/product/3017620422003/nutella-ferrero-nutella?fields=knowledge_panels](https://world.openfoodfacts.org/api/v2/product/3017620422003/nutella-ferrero-nutella?fields=knowledge_panels) this kp

**Comment by alexgarel** [comment]
Not like this, but just use same structure, do not add inexisting properties. Do not hesitate to ask question if you are in doubt.
