### ISSUE TITLE
Implement the simple hunger game knowledge panel

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#3]
It features  a text element with an link that points to hunger game questions corresponding to this facet.

To see supported facets, see hunger game filters in question game : https://hunger.openfoodfacts.org/

![image](https://user-images.githubusercontent.com/144788/177354075-9a3bb5fa-00f1-4c74-9baa-04039abe06bb.png)

It should reply with a response like (here for category beers):

```
{
  "knowledge_panels": [
    "hunger-game": {
      "elements": [
         {
           "element_type": "text",
           "text_element": {
             "html":"<p><a href=\"https://hunger.openfoodfacts.org/?type=category&value_tag=beers\">Answer  questions about category beer</a></p>\n"
           }
         }
      ]
    }
  ]
}
```

Key points:
* think about translations of texts (you may do it in another ticket)
* add tests

**Comment by sumit-158** [comment]
@alexgarel what exactly I have to do here? Is Its like implementing a new filter for the huger game other than the current one?

**Comment by sumit-158** [comment]
Is something like this
![image](https://user-images.githubusercontent.com/96618001/178251781-5c61327d-5b83-4d4c-9dd1-dcbe85339109.png)

**Comment by alexgarel** [comment]
> Is something like this

Yes. But you have to  filter because it does not work for every facets. 
Also if it's a country we filter on a country this is more a filter by country.
