### ISSUE TITLE
Prepare docker-compose for deployment

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#33]
- use external volumes
- do not use root in containers
- ...

**Comment by Aju100** [comment]
@alexgarel Hello, can I work on this issue ? I wanted to know more about this issue and contribute on this project

**Comment by alexgarel** [comment]
@Aju100 you are 100% welcome, let's do it :-)
Don't hesitate to join #community-portal channel on [our slack](https://slack.openfoodfacts.org/)

You might look at https://github.com/openfoodfacts/openfoodfacts-search/pull/17 to see how I added Makefile, modified Dockerfile and docker-compose.

We try to stick to same pattern in our repos (https://github.com/openfoodfacts/robotoff might also gives good insights).
