### ISSUE TITLE
Create CI to deploy to stagging

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#34]
### What
- Use GitHub Actions to deploy to staging
### Part of
- #14

**Comment by Aju100** [comment]
Hi, @alexgarel I would like to work on this issue. Can you give me much more reference on what are the things that need to carry out for the requirements?

**Comment by alexgarel** [comment]
Hi @Aju100, sorry I was AFK for more than one week and didn't see your message before leaving.
I think it's hard to delegate such task for now because we have to setup secrets on our servers that we are not ready to delegate.

**Comment by Aju100** [comment]
no worries @alexgarel

**Comment by sumit-158** [comment]
close in favour of #62
