### ISSUE TITLE
Review compliance with the knowledge panel API

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#39]
### What
This first implementation has taken some freedom for the knowledge panel API. Mainly because this one is not well documented.
We should ensure we are compatible with existing knowledge panel display:

* in the dart sdk : https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/model/KnowledgePanels.dart
* in the website: https://github.com/openfoodfacts/openfoodfacts-server/tree/main/templates/web/panels

**Comment by stephanegigandet** [comment]
I started to document the existing knowledge panel API in this PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/7406
