### ISSUE TITLE
Bullet points in README.md

### ISSUE THREAD

**Issue by sumit-158** [openfoodfacts/facets-knowledge-panels#54]
### What
- "why facets-knowledge-panels" in README shows topics in paragraph style on the [GitHub page](https://openfoodfacts.github.io/facets-knowledge-panels/) instead of a bullet points.
- Also add CONTRIBUTING.md inside doc/how-to-guides can take some inspiration from [here](https://github.com/openfoodfacts/hunger-games/blob/master/CONTRIBUTING.md)

### Screenshots
![image](https://user-images.githubusercontent.com/96618001/196877922-d5d038bb-67a8-4579-ba2c-129017322815.png)

**Comment by Aju100** [comment]
Hey @sumit-158 can i work on this issue ?

**Comment by sumit-158** [comment]
Sure go ahead ! :-)
