### ISSUE TITLE
If we don't give a value to the facet rendering seems anomalously long

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#70]
### What
Request to knowledge panels with a facet but no value seems really long compare to those with a value

### Steps to reproduce the behavior:

```bash
$ time curl -s "https://facets-kp.openfoodfacts.net/knowledge_panel?lang_code=fr&facet_tag=category" >/dev/null 
real	0m26,324s
```

```bash
$ time curl -s "https://facets-kp.openfoodfacts.net/knowledge_panel?lang_code=fr&facet_tag=category&value_tag=beers" >/dev/null 

real	0m0,672s
```

### Expected behavior
Requests should be equally fast.

I suspect there is a request we do that finish in error, thus we are waiting a lot. We should avoid this request if it is a wrong request.

**Comment by sumit-158** [comment]
@alexgarel I think it's mainly because of the request made for data-quality.

With just one facet like for a [category ](https://world.openfoodfacts.org/category/data-quality.json) it renders currently has 637 tags which of course takes time rather than with two facets like a [category with en:beer](https://world.openfoodfacts.org/category/en:beers/data-quality.json) has fewer data.

If we can add pagination to data-quality that would help to reduce rendering time.

**Comment by alexgarel** [comment]
https://world.openfoodfacts.org/category/data-quality.json?limit=10 seems to work but it's equally long ! (although it send back 8 items instead of 10)
```
$ time curl -s "https://world.openfoodfacts.org/category/data-quality.json?limit=10" > /dev/null

real	0m17,650s
```

but I think that asking for https://world.openfoodfacts.org/category/data-quality.json is equivalent to ask https://world.openfoodfacts.org/data-quality.json  (here as we do not filter on any value, the category is of no use).

So I think the best would be to:

1. simplify to remove the facet name if we don't have a facet value
2. use a caching mechanism to avoid fetching quality.json too much

For point 2, I would say that as a first approach we can make it simple:
* create a global_quality function
* use a module level variable _global_quality_cache where your store the time it was retrieved and the result (in a tuple)
* if the result is too old or empty, refetch, then assign the cache, else directly return the cache

**Comment by alexgarel** [comment]
Discussed today: use [lru_cache](https://docs.python.org/3.8/library/functools.html#functools.lru_cache) for the caching mechanism.
