### ISSUE TITLE
Make external services URLs configurable

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#71]
### Problem
We deployed the project to staging and it should use openfoodfacts.net so that we can detect problems ahead of production.
 
But openfoodfacts.org and hunger-games urls are hard coded in the project.

### Proposed solution
Make them a settings.

### Additional context

Right now we have a settings.py, that's fine. But I propose that for those parameters we use [the pydantic way of doing it](https://pydantic-docs.helpmanual.io/usage/settings/) (as [proposed by FastAPI](https://fastapi.tiangolo.com/advanced/settings/#pydantic-settings))

Remember to put those variables in the .env file and the docker-compose.yml (so that they are injected in the container)

**Comment by sumit-158** [comment]
Closing as #74 is merged!
