### ISSUE TITLE
Knowledge panel for data quality facet

### ISSUE THREAD

**Issue by sumit-158** [openfoodfacts/facets-knowledge-panels#9]
## Description
- Parse data-quality facet 
- Implement knowledge panel for this facet 
- Displaying information in two folds
 1 . presenting first top three problems
 2 . Then a link to view all problems 
 - some examples of data-quality facet
 https://world.openfoodfacts.org/category/meals/data-quality.json
 https://world.openfoodfacts.org/brand/lidl/data-quality.json

**Comment by alexgarel** [comment]
@sumit-158 do not forget to add issues to the "community federation portal" project (Projects panel on the right side). This helps tracking progress.
